# Generated by Django 4.2.6 on 2024-06-20 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("date_of_reg", models.DateField()),
                ("reg_number", models.CharField(max_length=255)),
                ("contact_person", models.CharField(max_length=255)),
                ("number_of_employees", models.IntegerField()),
                ("phonenumber", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "employee_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="talent.company"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talent.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_started", models.DateField(blank=True, null=True)),
                ("date_left", models.DateField(blank=True, null=True)),
                ("duties", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("changes_date", models.DateField()),
                ("change_type", models.CharField(max_length=255)),
                ("old_data_value", models.CharField(max_length=255)),
                ("new_data_value", models.CharField(max_length=255)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talent.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="talent.role"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="department",
            field=models.ManyToManyField(
                related_name="departments", to="talent.department"
            ),
        ),
    ]
